import type { Application } from '../types'

const today = (offsetDays: number) => {
  const d = new Date()
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().slice(0, 10)
}

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'seed-1',
    companyName: 'OCP Group',
    role: 'Data Analyst',
    location: 'Casablanca',
    jobUrl: 'https://www.ocpgroup.ma/careers',
    jobDescription:
      'Analyze production and logistics data, build dashboards, work with SQL and Python across the phosphate value chain.',
    score: 82,
    status: 'Interview',
    dateApplied: today(-18),
    dateLastUpdated: today(-3),
    resumeVersion: 'Resume_v3_DataAnalyst',
    coverLetterSent: true,
    contactPerson: 'Yasmine Alaoui — Talent Acquisition',
    salaryRange: '12,000 - 15,000 MAD',
    notes: 'First interview went well. Waiting on technical round scheduling.',
    source: 'LinkedIn',
  },
  {
    id: 'seed-2',
    companyName: 'Capgemini Maroc',
    role: 'Business Intelligence Consultant',
    location: 'Rabat',
    jobUrl: 'https://www.capgemini.com/ma-en/careers/',
    jobDescription:
      'Design BI solutions for European clients, Power BI, data modeling, occasional travel to France.',
    score: 71,
    status: 'Applied',
    dateApplied: today(-6),
    dateLastUpdated: today(-6),
    resumeVersion: 'Resume_v3_DataAnalyst',
    coverLetterSent: false,
    contactPerson: '',
    salaryRange: '',
    notes: 'Applied via referral from a former classmate.',
    source: 'Referral',
  },
  {
    id: 'seed-3',
    companyName: 'Yassir',
    role: 'Product Data Analyst',
    location: 'Casablanca — Hybrid',
    jobUrl: 'https://yassir.com/careers',
    jobDescription:
      'Own the metrics for the ride-hailing product line, SQL-heavy, direct exposure to product leadership.',
    score: 91,
    status: 'Technical Test',
    dateApplied: today(-25),
    dateLastUpdated: today(-1),
    resumeVersion: 'Resume_v4_Product',
    coverLetterSent: true,
    contactPerson: 'Karim B. — Engineering Manager',
    salaryRange: '14,000 - 18,000 MAD',
    notes: 'Take-home SQL + Python case due Friday.',
    source: 'Company Site',
  },
  {
    id: 'seed-4',
    companyName: 'Deloitte Maroc',
    role: 'Junior Data Consultant',
    location: 'Casablanca',
    jobUrl: 'https://www2.deloitte.com/ma/en/careers.html',
    jobDescription: 'Rotational analytics consulting role across banking and telecom clients.',
    score: 58,
    status: 'Rejected',
    dateApplied: today(-40),
    dateLastUpdated: today(-20),
    resumeVersion: 'Resume_v3_DataAnalyst',
    coverLetterSent: true,
    contactPerson: '',
    salaryRange: '',
    notes: 'Passed screening, rejected after case study round — feedback: wanted more consulting experience.',
    source: 'LinkedIn',
  },
  {
    id: 'seed-5',
    companyName: 'Emerging Startup (fintech, stealth)',
    role: 'Founding Data/Analytics Hire',
    location: 'Remote',
    jobUrl: '',
    jobDescription: 'Early hire building the analytics stack from scratch for a Morocco-based fintech.',
    score: 66,
    status: 'Wishlist',
    dateApplied: '',
    dateLastUpdated: today(-2),
    resumeVersion: '',
    coverLetterSent: false,
    contactPerson: 'Found via a founder friend, need to prep before reaching out.',
    salaryRange: '',
    notes: 'Research the product more before applying.',
    source: 'Networking Event',
  },
]
